// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: proto/camera_stream.proto

package hellopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CameraStream_ListCameras_FullMethodName     = "/camera.CameraStream/ListCameras"
	CameraStream_GetCamera_FullMethodName       = "/camera.CameraStream/GetCamera"
	CameraStream_RegisterCamera_FullMethodName  = "/camera.CameraStream/RegisterCamera"
	CameraStream_UpdateCamera_FullMethodName    = "/camera.CameraStream/UpdateCamera"
	CameraStream_DeleteCamera_FullMethodName    = "/camera.CameraStream/DeleteCamera"
	CameraStream_Negotiate_FullMethodName       = "/camera.CameraStream/Negotiate"
	CameraStream_StreamTelemetry_FullMethodName = "/camera.CameraStream/StreamTelemetry"
)

// CameraStreamClient is the client API for CameraStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CameraStream is the canonical camera service — a gRPC port of the legacy
// FastAPI backend (routers/cameras.py + services/camera_manager.py).
//
// gRPC carries control-plane traffic (registry CRUD, WebRTC signalling,
// telemetry streaming). Encoded video flows peer-to-peer over WebRTC from the
// DeepStream pipeline; browsers reach these methods through the small REST
// translation layer in `server/rest.go`.
type CameraStreamClient interface {
	// ── Registry (port of the legacy Mongo `cameras` collection CRUD) ──
	ListCameras(ctx context.Context, in *ListCamerasRequest, opts ...grpc.CallOption) (*ListCamerasResponse, error)
	GetCamera(ctx context.Context, in *GetCameraRequest, opts ...grpc.CallOption) (*Camera, error)
	RegisterCamera(ctx context.Context, in *RegisterCameraRequest, opts ...grpc.CallOption) (*Camera, error)
	UpdateCamera(ctx context.Context, in *UpdateCameraRequest, opts ...grpc.CallOption) (*Camera, error)
	DeleteCamera(ctx context.Context, in *DeleteCameraRequest, opts ...grpc.CallOption) (*DeleteCameraResponse, error)
	// ── WebRTC signalling (non-trickle ICE, single round-trip) ──
	// ── WebRTC signalling (non-trickle ICE, single round-trip) ──
	Negotiate(ctx context.Context, in *NegotiateRequest, opts ...grpc.CallOption) (*NegotiateResponse, error)
	// ── Live telemetry (port of the legacy 1 Hz WebSocket /ws/camera/{id}) ──
	StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySample], error)
}

type cameraStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewCameraStreamClient(cc grpc.ClientConnInterface) CameraStreamClient {
	return &cameraStreamClient{cc}
}

func (c *cameraStreamClient) ListCameras(ctx context.Context, in *ListCamerasRequest, opts ...grpc.CallOption) (*ListCamerasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCamerasResponse)
	err := c.cc.Invoke(ctx, CameraStream_ListCameras_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraStreamClient) GetCamera(ctx context.Context, in *GetCameraRequest, opts ...grpc.CallOption) (*Camera, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Camera)
	err := c.cc.Invoke(ctx, CameraStream_GetCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraStreamClient) RegisterCamera(ctx context.Context, in *RegisterCameraRequest, opts ...grpc.CallOption) (*Camera, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Camera)
	err := c.cc.Invoke(ctx, CameraStream_RegisterCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraStreamClient) UpdateCamera(ctx context.Context, in *UpdateCameraRequest, opts ...grpc.CallOption) (*Camera, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Camera)
	err := c.cc.Invoke(ctx, CameraStream_UpdateCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraStreamClient) DeleteCamera(ctx context.Context, in *DeleteCameraRequest, opts ...grpc.CallOption) (*DeleteCameraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCameraResponse)
	err := c.cc.Invoke(ctx, CameraStream_DeleteCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraStreamClient) Negotiate(ctx context.Context, in *NegotiateRequest, opts ...grpc.CallOption) (*NegotiateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiateResponse)
	err := c.cc.Invoke(ctx, CameraStream_Negotiate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cameraStreamClient) StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySample], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CameraStream_ServiceDesc.Streams[0], CameraStream_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRequest, TelemetrySample]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CameraStream_StreamTelemetryClient = grpc.ServerStreamingClient[TelemetrySample]

// CameraStreamServer is the server API for CameraStream service.
// All implementations must embed UnimplementedCameraStreamServer
// for forward compatibility.
//
// CameraStream is the canonical camera service — a gRPC port of the legacy
// FastAPI backend (routers/cameras.py + services/camera_manager.py).
//
// gRPC carries control-plane traffic (registry CRUD, WebRTC signalling,
// telemetry streaming). Encoded video flows peer-to-peer over WebRTC from the
// DeepStream pipeline; browsers reach these methods through the small REST
// translation layer in `server/rest.go`.
type CameraStreamServer interface {
	// ── Registry (port of the legacy Mongo `cameras` collection CRUD) ──
	ListCameras(context.Context, *ListCamerasRequest) (*ListCamerasResponse, error)
	GetCamera(context.Context, *GetCameraRequest) (*Camera, error)
	RegisterCamera(context.Context, *RegisterCameraRequest) (*Camera, error)
	UpdateCamera(context.Context, *UpdateCameraRequest) (*Camera, error)
	DeleteCamera(context.Context, *DeleteCameraRequest) (*DeleteCameraResponse, error)
	// ── WebRTC signalling (non-trickle ICE, single round-trip) ──
	// ── WebRTC signalling (non-trickle ICE, single round-trip) ──
	Negotiate(context.Context, *NegotiateRequest) (*NegotiateResponse, error)
	// ── Live telemetry (port of the legacy 1 Hz WebSocket /ws/camera/{id}) ──
	StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetrySample]) error
	mustEmbedUnimplementedCameraStreamServer()
}

// UnimplementedCameraStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCameraStreamServer struct{}

func (UnimplementedCameraStreamServer) ListCameras(context.Context, *ListCamerasRequest) (*ListCamerasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCameras not implemented")
}
func (UnimplementedCameraStreamServer) GetCamera(context.Context, *GetCameraRequest) (*Camera, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCamera not implemented")
}
func (UnimplementedCameraStreamServer) RegisterCamera(context.Context, *RegisterCameraRequest) (*Camera, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCamera not implemented")
}
func (UnimplementedCameraStreamServer) UpdateCamera(context.Context, *UpdateCameraRequest) (*Camera, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCamera not implemented")
}
func (UnimplementedCameraStreamServer) DeleteCamera(context.Context, *DeleteCameraRequest) (*DeleteCameraResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCamera not implemented")
}
func (UnimplementedCameraStreamServer) Negotiate(context.Context, *NegotiateRequest) (*NegotiateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Negotiate not implemented")
}
func (UnimplementedCameraStreamServer) StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetrySample]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedCameraStreamServer) mustEmbedUnimplementedCameraStreamServer() {}
func (UnimplementedCameraStreamServer) testEmbeddedByValue()                      {}

// UnsafeCameraStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CameraStreamServer will
// result in compilation errors.
type UnsafeCameraStreamServer interface {
	mustEmbedUnimplementedCameraStreamServer()
}

func RegisterCameraStreamServer(s grpc.ServiceRegistrar, srv CameraStreamServer) {
	// If the following call panics, it indicates UnimplementedCameraStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CameraStream_ServiceDesc, srv)
}

func _CameraStream_ListCameras_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCamerasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).ListCameras(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_ListCameras_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).ListCameras(ctx, req.(*ListCamerasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraStream_GetCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).GetCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_GetCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).GetCamera(ctx, req.(*GetCameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraStream_RegisterCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).RegisterCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_RegisterCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).RegisterCamera(ctx, req.(*RegisterCameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraStream_UpdateCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).UpdateCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_UpdateCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).UpdateCamera(ctx, req.(*UpdateCameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraStream_DeleteCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).DeleteCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_DeleteCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).DeleteCamera(ctx, req.(*DeleteCameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraStream_Negotiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegotiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CameraStreamServer).Negotiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CameraStream_Negotiate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CameraStreamServer).Negotiate(ctx, req.(*NegotiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CameraStream_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CameraStreamServer).StreamTelemetry(m, &grpc.GenericServerStream[TelemetryRequest, TelemetrySample]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CameraStream_StreamTelemetryServer = grpc.ServerStreamingServer[TelemetrySample]

// CameraStream_ServiceDesc is the grpc.ServiceDesc for CameraStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CameraStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "camera.CameraStream",
	HandlerType: (*CameraStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCameras",
			Handler:    _CameraStream_ListCameras_Handler,
		},
		{
			MethodName: "GetCamera",
			Handler:    _CameraStream_GetCamera_Handler,
		},
		{
			MethodName: "RegisterCamera",
			Handler:    _CameraStream_RegisterCamera_Handler,
		},
		{
			MethodName: "UpdateCamera",
			Handler:    _CameraStream_UpdateCamera_Handler,
		},
		{
			MethodName: "DeleteCamera",
			Handler:    _CameraStream_DeleteCamera_Handler,
		},
		{
			MethodName: "Negotiate",
			Handler:    _CameraStream_Negotiate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _CameraStream_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/camera_stream.proto",
}

const (
	ModelManager_ListModels_FullMethodName  = "/camera.ModelManager/ListModels"
	ModelManager_UploadModel_FullMethodName = "/camera.ModelManager/UploadModel"
	ModelManager_DeleteModel_FullMethodName = "/camera.ModelManager/DeleteModel"
)

// ModelManagerClient is the client API for ModelManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelManager ports the legacy /models endpoints. Packages are DeepStream
// bundles (nvinfer config + model + labels), not the old Python zips — see
// docs/MODEL_PACKAGE.md.
type ModelManagerClient interface {
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Unary base64 upload
	UploadModel(ctx context.Context, in *UploadModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
}

type modelManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewModelManagerClient(cc grpc.ClientConnInterface) ModelManagerClient {
	return &modelManagerClient{cc}
}

func (c *modelManagerClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelManager_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagerClient) UploadModel(ctx context.Context, in *UploadModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, ModelManager_UploadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagerClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, ModelManager_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelManagerServer is the server API for ModelManager service.
// All implementations must embed UnimplementedModelManagerServer
// for forward compatibility.
//
// ModelManager ports the legacy /models endpoints. Packages are DeepStream
// bundles (nvinfer config + model + labels), not the old Python zips — see
// docs/MODEL_PACKAGE.md.
type ModelManagerServer interface {
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Unary base64 upload
	UploadModel(context.Context, *UploadModelRequest) (*ModelInfo, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	mustEmbedUnimplementedModelManagerServer()
}

// UnimplementedModelManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelManagerServer struct{}

func (UnimplementedModelManagerServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelManagerServer) UploadModel(context.Context, *UploadModelRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadModel not implemented")
}
func (UnimplementedModelManagerServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedModelManagerServer) mustEmbedUnimplementedModelManagerServer() {}
func (UnimplementedModelManagerServer) testEmbeddedByValue()                      {}

// UnsafeModelManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelManagerServer will
// result in compilation errors.
type UnsafeModelManagerServer interface {
	mustEmbedUnimplementedModelManagerServer()
}

func RegisterModelManagerServer(s grpc.ServiceRegistrar, srv ModelManagerServer) {
	// If the following call panics, it indicates UnimplementedModelManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelManager_ServiceDesc, srv)
}

func _ModelManager_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagerServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManager_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagerServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManager_UploadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagerServer).UploadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManager_UploadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagerServer).UploadModel(ctx, req.(*UploadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManager_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagerServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManager_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagerServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelManager_ServiceDesc is the grpc.ServiceDesc for ModelManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "camera.ModelManager",
	HandlerType: (*ModelManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _ModelManager_ListModels_Handler,
		},
		{
			MethodName: "UploadModel",
			Handler:    _ModelManager_UploadModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _ModelManager_DeleteModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/camera_stream.proto",
}

const (
	IAMService_ListUsers_FullMethodName      = "/camera.IAMService/ListUsers"
	IAMService_UpdateUserRole_FullMethodName = "/camera.IAMService/UpdateUserRole"
	IAMService_RevokeAccess_FullMethodName   = "/camera.IAMService/RevokeAccess"
	IAMService_DeleteUser_FullMethodName     = "/camera.IAMService/DeleteUser"
)

// IAMServiceClient is the client API for IAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IAMServiceClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UserInfo, error)
	RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type iAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIAMServiceClient(cc grpc.ClientConnInterface) IAMServiceClient {
	return &iAMServiceClient{cc}
}

func (c *iAMServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, IAMService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, IAMService_UpdateUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAccessResponse)
	err := c.cc.Invoke(ctx, IAMService_RevokeAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, IAMService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAMServiceServer is the server API for IAMService service.
// All implementations must embed UnimplementedIAMServiceServer
// for forward compatibility.
type IAMServiceServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UserInfo, error)
	RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	mustEmbedUnimplementedIAMServiceServer()
}

// UnimplementedIAMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAMServiceServer struct{}

func (UnimplementedIAMServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedIAMServiceServer) UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedIAMServiceServer) RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedIAMServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedIAMServiceServer) mustEmbedUnimplementedIAMServiceServer() {}
func (UnimplementedIAMServiceServer) testEmbeddedByValue()                    {}

// UnsafeIAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAMServiceServer will
// result in compilation errors.
type UnsafeIAMServiceServer interface {
	mustEmbedUnimplementedIAMServiceServer()
}

func RegisterIAMServiceServer(s grpc.ServiceRegistrar, srv IAMServiceServer) {
	// If the following call panics, it indicates UnimplementedIAMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAMService_ServiceDesc, srv)
}

func _IAMService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).UpdateUserRole(ctx, req.(*UpdateUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RevokeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RevokeAccess(ctx, req.(*RevokeAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IAMService_ServiceDesc is the grpc.ServiceDesc for IAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "camera.IAMService",
	HandlerType: (*IAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _IAMService_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _IAMService_UpdateUserRole_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _IAMService_RevokeAccess_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _IAMService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/camera_stream.proto",
}

const (
	AnalyticsService_GetGlobalStats_FullMethodName = "/camera.AnalyticsService/GetGlobalStats"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetGlobalStats(ctx context.Context, in *GetGlobalStatsRequest, opts ...grpc.CallOption) (*GlobalStatsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetGlobalStats(ctx context.Context, in *GetGlobalStatsRequest, opts ...grpc.CallOption) (*GlobalStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetGlobalStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetGlobalStats(context.Context, *GetGlobalStatsRequest) (*GlobalStatsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetGlobalStats(context.Context, *GetGlobalStatsRequest) (*GlobalStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetGlobalStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetGlobalStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetGlobalStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetGlobalStats(ctx, req.(*GetGlobalStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "camera.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGlobalStats",
			Handler:    _AnalyticsService_GetGlobalStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/camera_stream.proto",
}
