// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "camera_stream.proto" (package "camera", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// ───────────────────────── Registry messages ─────────────────────────

/**
 * @generated from protobuf message camera.ListCamerasRequest
 */
export interface ListCamerasRequest {
}
/**
 * @generated from protobuf message camera.Camera
 */
export interface Camera {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string location = 3
     */
    location: string;
    /**
     * @generated from protobuf field: bool online = 4
     */
    online: boolean;
    /**
     * Input URI fed to the DeepStream pipeline (rtsp://…, file://…, http://…).
     *
     * @generated from protobuf field: string source = 5
     */
    source: string;
    /**
     * Model package id used for inference on this camera ("" = passthrough).
     *
     * @generated from protobuf field: string model_id = 6
     */
    modelId: string;
    /**
     * Roles allowed to view this camera's feed/telemetry. Empty = all roles.
     *
     * @generated from protobuf field: repeated string allowed_roles = 7
     */
    allowedRoles: string[];
}
/**
 * @generated from protobuf message camera.ListCamerasResponse
 */
export interface ListCamerasResponse {
    /**
     * @generated from protobuf field: repeated camera.Camera cameras = 1
     */
    cameras: Camera[];
}
/**
 * @generated from protobuf message camera.GetCameraRequest
 */
export interface GetCameraRequest {
    /**
     * @generated from protobuf field: string camera_id = 1
     */
    cameraId: string;
}
/**
 * @generated from protobuf message camera.RegisterCameraRequest
 */
export interface RegisterCameraRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string location = 2
     */
    location: string;
    /**
     * @generated from protobuf field: string source = 3
     */
    source: string;
    /**
     * @generated from protobuf field: string model_id = 4
     */
    modelId: string;
    /**
     * @generated from protobuf field: repeated string allowed_roles = 5
     */
    allowedRoles: string[];
}
/**
 * @generated from protobuf message camera.UpdateCameraRequest
 */
export interface UpdateCameraRequest {
    /**
     * @generated from protobuf field: string camera_id = 1
     */
    cameraId: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string location = 3
     */
    location: string;
    /**
     * @generated from protobuf field: string source = 4
     */
    source: string;
    /**
     * @generated from protobuf field: string model_id = 5
     */
    modelId: string;
    /**
     * @generated from protobuf field: repeated string allowed_roles = 6
     */
    allowedRoles: string[];
}
/**
 * @generated from protobuf message camera.DeleteCameraRequest
 */
export interface DeleteCameraRequest {
    /**
     * @generated from protobuf field: string camera_id = 1
     */
    cameraId: string;
}
/**
 * @generated from protobuf message camera.DeleteCameraResponse
 */
export interface DeleteCameraResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
// ───────────────────────── Signalling messages ─────────────────────────

/**
 * @generated from protobuf message camera.NegotiateRequest
 */
export interface NegotiateRequest {
    /**
     * @generated from protobuf field: string camera_id = 1
     */
    cameraId: string;
    /**
     * The browser's SDP offer (RTCSessionDescription.sdp).
     *
     * @generated from protobuf field: string sdp_offer = 2
     */
    sdpOffer: string;
}
/**
 * @generated from protobuf message camera.NegotiateResponse
 */
export interface NegotiateResponse {
    /**
     * The server's SDP answer (set as the browser's remote description).
     *
     * @generated from protobuf field: string sdp_answer = 1
     */
    sdpAnswer: string;
}
// ───────────────────────── Telemetry messages ─────────────────────────

/**
 * @generated from protobuf message camera.TelemetryRequest
 */
export interface TelemetryRequest {
    /**
     * @generated from protobuf field: string camera_id = 1
     */
    cameraId: string;
}
/**
 * @generated from protobuf message camera.Metric
 */
export interface Metric {
    /**
     * @generated from protobuf field: string label = 1
     */
    label: string;
    /**
     * @generated from protobuf field: string value = 2
     */
    value: string;
    /**
     * @generated from protobuf field: string unit = 3
     */
    unit: string;
    /**
     * @generated from protobuf field: string trend = 4
     */
    trend: string; // "up" | "down" | "neutral"
    /**
     * @generated from protobuf field: string color = 5
     */
    color: string; // "red" | "green" | "blue" | "default"
}
/**
 * @generated from protobuf message camera.TelemetrySample
 */
export interface TelemetrySample {
    /**
     * @generated from protobuf field: string camera_id = 1
     */
    cameraId: string;
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
    /**
     * @generated from protobuf field: double latency_ms = 3
     */
    latencyMs: number;
    /**
     * @generated from protobuf field: string model_id = 4
     */
    modelId: string;
    /**
     * @generated from protobuf field: bool alert = 5
     */
    alert: boolean;
    /**
     * @generated from protobuf field: string alert_reason = 6
     */
    alertReason: string;
    /**
     * @generated from protobuf field: repeated camera.Metric metrics = 7
     */
    metrics: Metric[];
    /**
     * @generated from protobuf field: double timestamp = 8
     */
    timestamp: number; // unix seconds
}
// ───────────────────────── Model messages ─────────────────────────

/**
 * @generated from protobuf message camera.ListModelsRequest
 */
export interface ListModelsRequest {
}
/**
 * @generated from protobuf message camera.ModelInfo
 */
export interface ModelInfo {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * Primary network file inside the package (relative path), e.g. model.onnx.
     *
     * @generated from protobuf field: string model_file = 4
     */
    modelFile: string;
    /**
     * nvinfer configuration file (relative path), e.g. config_infer_primary.txt.
     *
     * @generated from protobuf field: string config_file = 5
     */
    configFile: string;
    /**
     * @generated from protobuf field: string labels_file = 6
     */
    labelsFile: string;
    /**
     * @generated from protobuf field: bool builtin = 7
     */
    builtin: boolean; // built-ins cannot be deleted
}
/**
 * @generated from protobuf message camera.ListModelsResponse
 */
export interface ListModelsResponse {
    /**
     * @generated from protobuf field: repeated camera.ModelInfo models = 1
     */
    models: ModelInfo[];
}
/**
 * @generated from protobuf message camera.UploadModelMeta
 */
export interface UploadModelMeta {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
}
/**
 * @generated from protobuf message camera.UploadModelRequest
 */
export interface UploadModelRequest {
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "meta";
        /**
         * @generated from protobuf field: camera.UploadModelMeta meta = 1
         */
        meta: UploadModelMeta;
    } | {
        oneofKind: "chunk";
        /**
         * @generated from protobuf field: bytes chunk = 2
         */
        chunk: Uint8Array;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message camera.DeleteModelRequest
 */
export interface DeleteModelRequest {
    /**
     * @generated from protobuf field: string model_id = 1
     */
    modelId: string;
}
/**
 * @generated from protobuf message camera.DeleteModelResponse
 */
export interface DeleteModelResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class ListCamerasRequest$Type extends MessageType<ListCamerasRequest> {
    constructor() {
        super("camera.ListCamerasRequest", []);
    }
    create(value?: PartialMessage<ListCamerasRequest>): ListCamerasRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListCamerasRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListCamerasRequest): ListCamerasRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListCamerasRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.ListCamerasRequest
 */
export const ListCamerasRequest = new ListCamerasRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Camera$Type extends MessageType<Camera> {
    constructor() {
        super("camera.Camera", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "online", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "allowed_roles", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Camera>): Camera {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.location = "";
        message.online = false;
        message.source = "";
        message.modelId = "";
        message.allowedRoles = [];
        if (value !== undefined)
            reflectionMergePartial<Camera>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Camera): Camera {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string location */ 3:
                    message.location = reader.string();
                    break;
                case /* bool online */ 4:
                    message.online = reader.bool();
                    break;
                case /* string source */ 5:
                    message.source = reader.string();
                    break;
                case /* string model_id */ 6:
                    message.modelId = reader.string();
                    break;
                case /* repeated string allowed_roles */ 7:
                    message.allowedRoles.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Camera, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string location = 3; */
        if (message.location !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.location);
        /* bool online = 4; */
        if (message.online !== false)
            writer.tag(4, WireType.Varint).bool(message.online);
        /* string source = 5; */
        if (message.source !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.source);
        /* string model_id = 6; */
        if (message.modelId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.modelId);
        /* repeated string allowed_roles = 7; */
        for (let i = 0; i < message.allowedRoles.length; i++)
            writer.tag(7, WireType.LengthDelimited).string(message.allowedRoles[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.Camera
 */
export const Camera = new Camera$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListCamerasResponse$Type extends MessageType<ListCamerasResponse> {
    constructor() {
        super("camera.ListCamerasResponse", [
            { no: 1, name: "cameras", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Camera }
        ]);
    }
    create(value?: PartialMessage<ListCamerasResponse>): ListCamerasResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cameras = [];
        if (value !== undefined)
            reflectionMergePartial<ListCamerasResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListCamerasResponse): ListCamerasResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated camera.Camera cameras */ 1:
                    message.cameras.push(Camera.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListCamerasResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated camera.Camera cameras = 1; */
        for (let i = 0; i < message.cameras.length; i++)
            Camera.internalBinaryWrite(message.cameras[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.ListCamerasResponse
 */
export const ListCamerasResponse = new ListCamerasResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCameraRequest$Type extends MessageType<GetCameraRequest> {
    constructor() {
        super("camera.GetCameraRequest", [
            { no: 1, name: "camera_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetCameraRequest>): GetCameraRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cameraId = "";
        if (value !== undefined)
            reflectionMergePartial<GetCameraRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCameraRequest): GetCameraRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string camera_id */ 1:
                    message.cameraId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCameraRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string camera_id = 1; */
        if (message.cameraId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cameraId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.GetCameraRequest
 */
export const GetCameraRequest = new GetCameraRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterCameraRequest$Type extends MessageType<RegisterCameraRequest> {
    constructor() {
        super("camera.RegisterCameraRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "allowed_roles", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterCameraRequest>): RegisterCameraRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.location = "";
        message.source = "";
        message.modelId = "";
        message.allowedRoles = [];
        if (value !== undefined)
            reflectionMergePartial<RegisterCameraRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterCameraRequest): RegisterCameraRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string location */ 2:
                    message.location = reader.string();
                    break;
                case /* string source */ 3:
                    message.source = reader.string();
                    break;
                case /* string model_id */ 4:
                    message.modelId = reader.string();
                    break;
                case /* repeated string allowed_roles */ 5:
                    message.allowedRoles.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterCameraRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string location = 2; */
        if (message.location !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.location);
        /* string source = 3; */
        if (message.source !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.source);
        /* string model_id = 4; */
        if (message.modelId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.modelId);
        /* repeated string allowed_roles = 5; */
        for (let i = 0; i < message.allowedRoles.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.allowedRoles[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.RegisterCameraRequest
 */
export const RegisterCameraRequest = new RegisterCameraRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateCameraRequest$Type extends MessageType<UpdateCameraRequest> {
    constructor() {
        super("camera.UpdateCameraRequest", [
            { no: 1, name: "camera_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "allowed_roles", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateCameraRequest>): UpdateCameraRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cameraId = "";
        message.name = "";
        message.location = "";
        message.source = "";
        message.modelId = "";
        message.allowedRoles = [];
        if (value !== undefined)
            reflectionMergePartial<UpdateCameraRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateCameraRequest): UpdateCameraRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string camera_id */ 1:
                    message.cameraId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string location */ 3:
                    message.location = reader.string();
                    break;
                case /* string source */ 4:
                    message.source = reader.string();
                    break;
                case /* string model_id */ 5:
                    message.modelId = reader.string();
                    break;
                case /* repeated string allowed_roles */ 6:
                    message.allowedRoles.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateCameraRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string camera_id = 1; */
        if (message.cameraId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cameraId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string location = 3; */
        if (message.location !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.location);
        /* string source = 4; */
        if (message.source !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.source);
        /* string model_id = 5; */
        if (message.modelId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.modelId);
        /* repeated string allowed_roles = 6; */
        for (let i = 0; i < message.allowedRoles.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.allowedRoles[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.UpdateCameraRequest
 */
export const UpdateCameraRequest = new UpdateCameraRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteCameraRequest$Type extends MessageType<DeleteCameraRequest> {
    constructor() {
        super("camera.DeleteCameraRequest", [
            { no: 1, name: "camera_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteCameraRequest>): DeleteCameraRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cameraId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteCameraRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteCameraRequest): DeleteCameraRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string camera_id */ 1:
                    message.cameraId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteCameraRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string camera_id = 1; */
        if (message.cameraId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cameraId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.DeleteCameraRequest
 */
export const DeleteCameraRequest = new DeleteCameraRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteCameraResponse$Type extends MessageType<DeleteCameraResponse> {
    constructor() {
        super("camera.DeleteCameraResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteCameraResponse>): DeleteCameraResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteCameraResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteCameraResponse): DeleteCameraResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteCameraResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.DeleteCameraResponse
 */
export const DeleteCameraResponse = new DeleteCameraResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NegotiateRequest$Type extends MessageType<NegotiateRequest> {
    constructor() {
        super("camera.NegotiateRequest", [
            { no: 1, name: "camera_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sdp_offer", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NegotiateRequest>): NegotiateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cameraId = "";
        message.sdpOffer = "";
        if (value !== undefined)
            reflectionMergePartial<NegotiateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NegotiateRequest): NegotiateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string camera_id */ 1:
                    message.cameraId = reader.string();
                    break;
                case /* string sdp_offer */ 2:
                    message.sdpOffer = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NegotiateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string camera_id = 1; */
        if (message.cameraId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cameraId);
        /* string sdp_offer = 2; */
        if (message.sdpOffer !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.sdpOffer);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.NegotiateRequest
 */
export const NegotiateRequest = new NegotiateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NegotiateResponse$Type extends MessageType<NegotiateResponse> {
    constructor() {
        super("camera.NegotiateResponse", [
            { no: 1, name: "sdp_answer", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NegotiateResponse>): NegotiateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sdpAnswer = "";
        if (value !== undefined)
            reflectionMergePartial<NegotiateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NegotiateResponse): NegotiateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string sdp_answer */ 1:
                    message.sdpAnswer = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NegotiateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string sdp_answer = 1; */
        if (message.sdpAnswer !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sdpAnswer);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.NegotiateResponse
 */
export const NegotiateResponse = new NegotiateResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryRequest$Type extends MessageType<TelemetryRequest> {
    constructor() {
        super("camera.TelemetryRequest", [
            { no: 1, name: "camera_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TelemetryRequest>): TelemetryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cameraId = "";
        if (value !== undefined)
            reflectionMergePartial<TelemetryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryRequest): TelemetryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string camera_id */ 1:
                    message.cameraId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string camera_id = 1; */
        if (message.cameraId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cameraId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.TelemetryRequest
 */
export const TelemetryRequest = new TelemetryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Metric$Type extends MessageType<Metric> {
    constructor() {
        super("camera.Metric", [
            { no: 1, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "unit", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "trend", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Metric>): Metric {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.label = "";
        message.value = "";
        message.unit = "";
        message.trend = "";
        message.color = "";
        if (value !== undefined)
            reflectionMergePartial<Metric>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Metric): Metric {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string label */ 1:
                    message.label = reader.string();
                    break;
                case /* string value */ 2:
                    message.value = reader.string();
                    break;
                case /* string unit */ 3:
                    message.unit = reader.string();
                    break;
                case /* string trend */ 4:
                    message.trend = reader.string();
                    break;
                case /* string color */ 5:
                    message.color = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Metric, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string label = 1; */
        if (message.label !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.label);
        /* string value = 2; */
        if (message.value !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.value);
        /* string unit = 3; */
        if (message.unit !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.unit);
        /* string trend = 4; */
        if (message.trend !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.trend);
        /* string color = 5; */
        if (message.color !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.color);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.Metric
 */
export const Metric = new Metric$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetrySample$Type extends MessageType<TelemetrySample> {
    constructor() {
        super("camera.TelemetrySample", [
            { no: 1, name: "camera_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "latency_ms", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "alert", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "alert_reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "metrics", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Metric },
            { no: 8, name: "timestamp", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<TelemetrySample>): TelemetrySample {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cameraId = "";
        message.count = 0;
        message.latencyMs = 0;
        message.modelId = "";
        message.alert = false;
        message.alertReason = "";
        message.metrics = [];
        message.timestamp = 0;
        if (value !== undefined)
            reflectionMergePartial<TelemetrySample>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetrySample): TelemetrySample {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string camera_id */ 1:
                    message.cameraId = reader.string();
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                case /* double latency_ms */ 3:
                    message.latencyMs = reader.double();
                    break;
                case /* string model_id */ 4:
                    message.modelId = reader.string();
                    break;
                case /* bool alert */ 5:
                    message.alert = reader.bool();
                    break;
                case /* string alert_reason */ 6:
                    message.alertReason = reader.string();
                    break;
                case /* repeated camera.Metric metrics */ 7:
                    message.metrics.push(Metric.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* double timestamp */ 8:
                    message.timestamp = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetrySample, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string camera_id = 1; */
        if (message.cameraId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cameraId);
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        /* double latency_ms = 3; */
        if (message.latencyMs !== 0)
            writer.tag(3, WireType.Bit64).double(message.latencyMs);
        /* string model_id = 4; */
        if (message.modelId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.modelId);
        /* bool alert = 5; */
        if (message.alert !== false)
            writer.tag(5, WireType.Varint).bool(message.alert);
        /* string alert_reason = 6; */
        if (message.alertReason !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.alertReason);
        /* repeated camera.Metric metrics = 7; */
        for (let i = 0; i < message.metrics.length; i++)
            Metric.internalBinaryWrite(message.metrics[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* double timestamp = 8; */
        if (message.timestamp !== 0)
            writer.tag(8, WireType.Bit64).double(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.TelemetrySample
 */
export const TelemetrySample = new TelemetrySample$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListModelsRequest$Type extends MessageType<ListModelsRequest> {
    constructor() {
        super("camera.ListModelsRequest", []);
    }
    create(value?: PartialMessage<ListModelsRequest>): ListModelsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListModelsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListModelsRequest): ListModelsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListModelsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.ListModelsRequest
 */
export const ListModelsRequest = new ListModelsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ModelInfo$Type extends MessageType<ModelInfo> {
    constructor() {
        super("camera.ModelInfo", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "model_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "config_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "labels_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "builtin", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ModelInfo>): ModelInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.description = "";
        message.modelFile = "";
        message.configFile = "";
        message.labelsFile = "";
        message.builtin = false;
        if (value !== undefined)
            reflectionMergePartial<ModelInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ModelInfo): ModelInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string model_file */ 4:
                    message.modelFile = reader.string();
                    break;
                case /* string config_file */ 5:
                    message.configFile = reader.string();
                    break;
                case /* string labels_file */ 6:
                    message.labelsFile = reader.string();
                    break;
                case /* bool builtin */ 7:
                    message.builtin = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ModelInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string model_file = 4; */
        if (message.modelFile !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.modelFile);
        /* string config_file = 5; */
        if (message.configFile !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.configFile);
        /* string labels_file = 6; */
        if (message.labelsFile !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.labelsFile);
        /* bool builtin = 7; */
        if (message.builtin !== false)
            writer.tag(7, WireType.Varint).bool(message.builtin);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.ModelInfo
 */
export const ModelInfo = new ModelInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListModelsResponse$Type extends MessageType<ListModelsResponse> {
    constructor() {
        super("camera.ListModelsResponse", [
            { no: 1, name: "models", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ModelInfo }
        ]);
    }
    create(value?: PartialMessage<ListModelsResponse>): ListModelsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.models = [];
        if (value !== undefined)
            reflectionMergePartial<ListModelsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListModelsResponse): ListModelsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated camera.ModelInfo models */ 1:
                    message.models.push(ModelInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListModelsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated camera.ModelInfo models = 1; */
        for (let i = 0; i < message.models.length; i++)
            ModelInfo.internalBinaryWrite(message.models[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.ListModelsResponse
 */
export const ListModelsResponse = new ListModelsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UploadModelMeta$Type extends MessageType<UploadModelMeta> {
    constructor() {
        super("camera.UploadModelMeta", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UploadModelMeta>): UploadModelMeta {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<UploadModelMeta>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UploadModelMeta): UploadModelMeta {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UploadModelMeta, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.UploadModelMeta
 */
export const UploadModelMeta = new UploadModelMeta$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UploadModelRequest$Type extends MessageType<UploadModelRequest> {
    constructor() {
        super("camera.UploadModelRequest", [
            { no: 1, name: "meta", kind: "message", oneof: "payload", T: () => UploadModelMeta },
            { no: 2, name: "chunk", kind: "scalar", oneof: "payload", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<UploadModelRequest>): UploadModelRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.payload = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<UploadModelRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UploadModelRequest): UploadModelRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* camera.UploadModelMeta meta */ 1:
                    message.payload = {
                        oneofKind: "meta",
                        meta: UploadModelMeta.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).meta)
                    };
                    break;
                case /* bytes chunk */ 2:
                    message.payload = {
                        oneofKind: "chunk",
                        chunk: reader.bytes()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UploadModelRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* camera.UploadModelMeta meta = 1; */
        if (message.payload.oneofKind === "meta")
            UploadModelMeta.internalBinaryWrite(message.payload.meta, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bytes chunk = 2; */
        if (message.payload.oneofKind === "chunk")
            writer.tag(2, WireType.LengthDelimited).bytes(message.payload.chunk);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.UploadModelRequest
 */
export const UploadModelRequest = new UploadModelRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteModelRequest$Type extends MessageType<DeleteModelRequest> {
    constructor() {
        super("camera.DeleteModelRequest", [
            { no: 1, name: "model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteModelRequest>): DeleteModelRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.modelId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteModelRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteModelRequest): DeleteModelRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string model_id */ 1:
                    message.modelId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteModelRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string model_id = 1; */
        if (message.modelId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.modelId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.DeleteModelRequest
 */
export const DeleteModelRequest = new DeleteModelRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteModelResponse$Type extends MessageType<DeleteModelResponse> {
    constructor() {
        super("camera.DeleteModelResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteModelResponse>): DeleteModelResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteModelResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteModelResponse): DeleteModelResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteModelResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message camera.DeleteModelResponse
 */
export const DeleteModelResponse = new DeleteModelResponse$Type();
/**
 * @generated ServiceType for protobuf service camera.CameraStream
 */
export const CameraStream = new ServiceType("camera.CameraStream", [
    { name: "ListCameras", options: {}, I: ListCamerasRequest, O: ListCamerasResponse },
    { name: "GetCamera", options: {}, I: GetCameraRequest, O: Camera },
    { name: "RegisterCamera", options: {}, I: RegisterCameraRequest, O: Camera },
    { name: "UpdateCamera", options: {}, I: UpdateCameraRequest, O: Camera },
    { name: "DeleteCamera", options: {}, I: DeleteCameraRequest, O: DeleteCameraResponse },
    { name: "Negotiate", options: {}, I: NegotiateRequest, O: NegotiateResponse },
    { name: "StreamTelemetry", serverStreaming: true, options: {}, I: TelemetryRequest, O: TelemetrySample }
]);
/**
 * @generated ServiceType for protobuf service camera.ModelManager
 */
export const ModelManager = new ServiceType("camera.ModelManager", [
    { name: "ListModels", options: {}, I: ListModelsRequest, O: ListModelsResponse },
    { name: "UploadModel", clientStreaming: true, options: {}, I: UploadModelRequest, O: ModelInfo },
    { name: "DeleteModel", options: {}, I: DeleteModelRequest, O: DeleteModelResponse }
]);
