// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "camera_stream.proto" (package "camera", syntax proto3)
// tslint:disable
import { ModelManager } from "./camera_stream";
import type { DeleteModelResponse } from "./camera_stream";
import type { DeleteModelRequest } from "./camera_stream";
import type { ModelInfo } from "./camera_stream";
import type { UploadModelRequest } from "./camera_stream";
import type { ClientStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { ListModelsResponse } from "./camera_stream";
import type { ListModelsRequest } from "./camera_stream";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CameraStream } from "./camera_stream";
import type { TelemetrySample } from "./camera_stream";
import type { TelemetryRequest } from "./camera_stream";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { NegotiateResponse } from "./camera_stream";
import type { NegotiateRequest } from "./camera_stream";
import type { DeleteCameraResponse } from "./camera_stream";
import type { DeleteCameraRequest } from "./camera_stream";
import type { UpdateCameraRequest } from "./camera_stream";
import type { RegisterCameraRequest } from "./camera_stream";
import type { Camera } from "./camera_stream";
import type { GetCameraRequest } from "./camera_stream";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListCamerasResponse } from "./camera_stream";
import type { ListCamerasRequest } from "./camera_stream";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * CameraStream is the canonical camera service — a gRPC port of the legacy
 * FastAPI backend (routers/cameras.py + services/camera_manager.py).
 *
 * gRPC carries control-plane traffic (registry CRUD, WebRTC signalling,
 * telemetry streaming). Encoded video flows peer-to-peer over WebRTC from the
 * DeepStream pipeline; browsers reach these methods through the small REST
 * translation layer in `server/rest.go`.
 *
 * @generated from protobuf service camera.CameraStream
 */
export interface ICameraStreamClient {
    /**
     * ── Registry (port of the legacy Mongo `cameras` collection CRUD) ──
     *
     * @generated from protobuf rpc: ListCameras
     */
    listCameras(input: ListCamerasRequest, options?: RpcOptions): UnaryCall<ListCamerasRequest, ListCamerasResponse>;
    /**
     * @generated from protobuf rpc: GetCamera
     */
    getCamera(input: GetCameraRequest, options?: RpcOptions): UnaryCall<GetCameraRequest, Camera>;
    /**
     * @generated from protobuf rpc: RegisterCamera
     */
    registerCamera(input: RegisterCameraRequest, options?: RpcOptions): UnaryCall<RegisterCameraRequest, Camera>;
    /**
     * @generated from protobuf rpc: UpdateCamera
     */
    updateCamera(input: UpdateCameraRequest, options?: RpcOptions): UnaryCall<UpdateCameraRequest, Camera>;
    /**
     * @generated from protobuf rpc: DeleteCamera
     */
    deleteCamera(input: DeleteCameraRequest, options?: RpcOptions): UnaryCall<DeleteCameraRequest, DeleteCameraResponse>;
    /**
     * ── WebRTC signalling (non-trickle ICE, single round-trip) ──
     *
     * @generated from protobuf rpc: Negotiate
     */
    negotiate(input: NegotiateRequest, options?: RpcOptions): UnaryCall<NegotiateRequest, NegotiateResponse>;
    /**
     * ── Live telemetry (port of the legacy 1 Hz WebSocket /ws/camera/{id}) ──
     *
     * @generated from protobuf rpc: StreamTelemetry
     */
    streamTelemetry(input: TelemetryRequest, options?: RpcOptions): ServerStreamingCall<TelemetryRequest, TelemetrySample>;
}
/**
 * CameraStream is the canonical camera service — a gRPC port of the legacy
 * FastAPI backend (routers/cameras.py + services/camera_manager.py).
 *
 * gRPC carries control-plane traffic (registry CRUD, WebRTC signalling,
 * telemetry streaming). Encoded video flows peer-to-peer over WebRTC from the
 * DeepStream pipeline; browsers reach these methods through the small REST
 * translation layer in `server/rest.go`.
 *
 * @generated from protobuf service camera.CameraStream
 */
export class CameraStreamClient implements ICameraStreamClient, ServiceInfo {
    typeName = CameraStream.typeName;
    methods = CameraStream.methods;
    options = CameraStream.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * ── Registry (port of the legacy Mongo `cameras` collection CRUD) ──
     *
     * @generated from protobuf rpc: ListCameras
     */
    listCameras(input: ListCamerasRequest, options?: RpcOptions): UnaryCall<ListCamerasRequest, ListCamerasResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCamerasRequest, ListCamerasResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCamera
     */
    getCamera(input: GetCameraRequest, options?: RpcOptions): UnaryCall<GetCameraRequest, Camera> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCameraRequest, Camera>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterCamera
     */
    registerCamera(input: RegisterCameraRequest, options?: RpcOptions): UnaryCall<RegisterCameraRequest, Camera> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterCameraRequest, Camera>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateCamera
     */
    updateCamera(input: UpdateCameraRequest, options?: RpcOptions): UnaryCall<UpdateCameraRequest, Camera> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateCameraRequest, Camera>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCamera
     */
    deleteCamera(input: DeleteCameraRequest, options?: RpcOptions): UnaryCall<DeleteCameraRequest, DeleteCameraResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCameraRequest, DeleteCameraResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── WebRTC signalling (non-trickle ICE, single round-trip) ──
     *
     * @generated from protobuf rpc: Negotiate
     */
    negotiate(input: NegotiateRequest, options?: RpcOptions): UnaryCall<NegotiateRequest, NegotiateResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<NegotiateRequest, NegotiateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ── Live telemetry (port of the legacy 1 Hz WebSocket /ws/camera/{id}) ──
     *
     * @generated from protobuf rpc: StreamTelemetry
     */
    streamTelemetry(input: TelemetryRequest, options?: RpcOptions): ServerStreamingCall<TelemetryRequest, TelemetrySample> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<TelemetryRequest, TelemetrySample>("serverStreaming", this._transport, method, opt, input);
    }
}
/**
 * ModelManager ports the legacy /models endpoints. Packages are DeepStream
 * bundles (nvinfer config + model + labels), not the old Python zips — see
 * docs/MODEL_PACKAGE.md.
 *
 * @generated from protobuf service camera.ModelManager
 */
export interface IModelManagerClient {
    /**
     * @generated from protobuf rpc: ListModels
     */
    listModels(input: ListModelsRequest, options?: RpcOptions): UnaryCall<ListModelsRequest, ListModelsResponse>;
    /**
     * Client-streaming upload: first message must carry `meta`, the rest carry
     * `chunk` bytes of the zip archive.
     *
     * @generated from protobuf rpc: UploadModel
     */
    uploadModel(options?: RpcOptions): ClientStreamingCall<UploadModelRequest, ModelInfo>;
    /**
     * @generated from protobuf rpc: DeleteModel
     */
    deleteModel(input: DeleteModelRequest, options?: RpcOptions): UnaryCall<DeleteModelRequest, DeleteModelResponse>;
}
/**
 * ModelManager ports the legacy /models endpoints. Packages are DeepStream
 * bundles (nvinfer config + model + labels), not the old Python zips — see
 * docs/MODEL_PACKAGE.md.
 *
 * @generated from protobuf service camera.ModelManager
 */
export class ModelManagerClient implements IModelManagerClient, ServiceInfo {
    typeName = ModelManager.typeName;
    methods = ModelManager.methods;
    options = ModelManager.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListModels
     */
    listModels(input: ListModelsRequest, options?: RpcOptions): UnaryCall<ListModelsRequest, ListModelsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListModelsRequest, ListModelsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Client-streaming upload: first message must carry `meta`, the rest carry
     * `chunk` bytes of the zip archive.
     *
     * @generated from protobuf rpc: UploadModel
     */
    uploadModel(options?: RpcOptions): ClientStreamingCall<UploadModelRequest, ModelInfo> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UploadModelRequest, ModelInfo>("clientStreaming", this._transport, method, opt);
    }
    /**
     * @generated from protobuf rpc: DeleteModel
     */
    deleteModel(input: DeleteModelRequest, options?: RpcOptions): UnaryCall<DeleteModelRequest, DeleteModelResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteModelRequest, DeleteModelResponse>("unary", this._transport, method, opt, input);
    }
}
